version: '3.4'

volumes:
  appdata:
  custom:

services:
  blogengine.net:
    image: jodelac/blogenginenet
    build:
      context: .\BlogEngine.NET
      dockerfile: Dockerfile
    volumes:
      - appdata:C:\inetpub\wwwroot\App_Data
      - custom:C:\inetpub\wwwroot\Custom